// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero';
import NavigationItem from './NavigationItem';

export {
	Hero,
	NavigationItem,
};

export const components = {
	hero: Hero,
	navigation_item: NavigationItem,
};
